name: charge_mod
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  dots_indicator: ^3.0.0
  country_code_picker: ^3.0.0
  dio: ^5.4.0
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svgs/
    - assets/images/
    - assets/icons/

  fonts:
    - family: ABeeZee-Regular
      fonts:
        - asset: assets/fonts/ABeeZee-Regular.ttf
          weight: 400
    - family: AirbnbCereal
      fonts:
        - asset: assets/fonts/AirbnbCereal_W_Bd.otf
          weight: 500
        - asset: assets/fonts/AirbnbCereal_W_Lt.otf
          weight: 200
        - asset: assets/fonts/AirbnbCereal_W_Md.otf
          weight: 300
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
